[project]
name = "current-train-info-bot"
version = "0.1.0"
description = "App for Crawling current traffic info of train and Displaying"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "flask>=3.1.1",
    "pyyaml>=6.0.2",
    "tqdm>=4.67.1",
]
